version: 2
jobs:
  build:
    docker:
      - image: busybox:1.27
    steps:
      - checkout
      - run:
          # Get terraform binary
          command: |
            TF_VERSION=${TF_VERSION:-"0.10.8"}
            wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
            unzip terraform_${TF_VERSION}_linux_amd64.zip -d /bin
      - run:
          # Delete symlinks for backend configuration as we OK with local state files here.
          command: |
            rm -f platforms/azure/giantnetes/backend.tf
            rm -f platforms/azure/giantnetes-cloud-config/backend.tf
            rm -f platforms/aws/giantnetes/backend.tf
            rm -f platforms/aws/giantnetes/provider.tf
      - run:
          # Run terraform syntax check
          command: terraform fmt -write=false -diff=true -check=true

  e2eTestAWS:
    docker:
      - image: quay.io/giantswarm/docker-terraform-and-stuff:latest
    steps:
    - checkout
    - run: ./misc/e2e-aws.sh

workflows:
  version: 2
  build_e2e:
    jobs:

      - build

      - hold:
          type: approval
          filters:
            branches:
              ignore: master
          requires:
          - build

      - e2eTestAWS:
          requires:
          - hold
