version: 2
jobs:
  build:
    docker:
      - image: quay.io/giantswarm/docker-terraform-and-stuff:latest
    steps:
      - checkout
      - run:
          # Get terraform binary
          command: |
            TF_VERSION=${TF_VERSION:-"0.12.1"}
            wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
            unzip -o terraform_${TF_VERSION}_linux_amd64.zip -d /bin
      - run:
          # Delete symlinks for backend configuration as we OK with local state files here.
          command: |
            rm -f platforms/azure/giantnetes/backend.tf
            rm -f platforms/azure/giantnetes-cloud-config/backend.tf
            rm -f platforms/aws/giantnetes/backend.tf
            rm -f platforms/aws/giantnetes/provider.tf
      - run:
          # Run terraform syntax check
          command: terraform fmt -write=false -diff=true -check=true

  e2eTestAWSMultiMaster: &e2eTestAWSMultiMaster
    docker:
      - image: quay.io/giantswarm/docker-terraform-and-stuff:latest
    environment:
      MASTER_COUNT: 3
    steps:
    - checkout
    - run: ./misc/e2e-aws.sh

  e2eTestAWSMaster:
    environment:
      E2E_ENABLE_CONFORMANCE: "no"
    <<: *e2eTestAWSMultiMaster

  e2eTestAzureMultiMaster: &e2eTestAzureMultiMaster
    docker:
      - image: quay.io/giantswarm/docker-terraform-and-stuff:latest
    environment:
      MASTER_COUNT: 3
    steps:
    - checkout
    - run: ./misc/e2e-azure.sh

  e2eTestAzureMaster:
    environment:
      E2E_ENABLE_CONFORMANCE: "no"
    <<: *e2eTestAzureMultiMaster

workflows:
  version: 2
  build_e2e:
    jobs:

      - build

      - hold:
          type: approval
          filters:
            branches:
              ignore: master
          requires:
          - build

      - e2eTestAWSMultiMaster:
          requires:
          - hold

      - e2eTestAzureMultiMaster:
          requires:
          - hold

      # Test w/o approval for master branch.
      - e2eTestAWSMaster:
          filters:
            branches:
              only: master
          requires:
          - build

      # Test w/o approval for master branch.
      - e2eTestAzureMaster:
          filters:
            branches:
              only: master
          requires:
          - build
