version: 2
jobs:
  build:
    docker:
      - image: alpine:3.8
    steps:
      - checkout
      - run:
          # Get terraform binary
          command: |
            TF_VERSION=${TF_VERSION:-"0.11.7"}
            wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
            unzip terraform_${TF_VERSION}_linux_amd64.zip -d /bin
      - run:
          # Delete symlinks for backend configuration as we OK with local state files here.
          command: |
            rm -f platforms/azure/giantnetes/backend.tf
            rm -f platforms/azure/giantnetes-cloud-config/backend.tf
            rm -f platforms/aws/giantnetes/backend.tf
            rm -f platforms/aws/giantnetes/provider.tf
      - run:
          # Run terraform syntax check
          command: terraform fmt -write=false -diff=true -check=true

  e2eTestAWS: &e2eTestAWS
    docker:
      - image: quay.io/giantswarm/docker-terraform-and-stuff
    steps:
    - checkout
    - run: ./misc/e2e-aws.sh

  e2eTestAWSMaster:
    environment:
      E2E_ENABLE_CONFORMANCE: "yes"
    <<: *e2eTestAWS

  e2eTestAzure: &e2eTestAzure
    docker:
      - image: quay.io/giantswarm/docker-terraform-and-stuff
    steps:
    - checkout
    - run: ./misc/e2e-azure.sh

  e2eTestAzureMaster:
    environment:
      E2E_ENABLE_CONFORMANCE: "yes"
    <<: *e2eTestAzure

workflows:
  version: 2
  build_e2e:
    jobs:

      - build

      - hold:
          type: approval
          filters:
            branches:
              ignore: master
          requires:
          - build

      - e2eTestAWS:
          requires:
          - hold

      - e2eTestAzure:
          requires:
          - hold

      # Test w/o approval for master branch.
      - e2eTestAWSMaster:
          filters:
            branches:
              only: master
          requires:
          - build

      # Test w/o approval for master branch.
      - e2eTestAzureMaster:
          filters:
            branches:
              only: master
          requires:
          - build
