apiVersion: v1
clusters:
- cluster:
    server: http://0.0.0.0:{{ .K8SAuditWebhookPort }}/auditk8s
  name: audit-webhook-service
contexts:
- context:
    cluster: audit-webhook-service
    user: ""
  name: default-context
current-context: default-context
kind: Config
preferences: {}
users: []