cloud: {{ .AzureCloud }}
tenantId: {{ .AzureSPTenantID }}
subscriptionId: {{ .AzureSPSubscriptionID }}
aadClientId: {{ .AzureSPAADClientID }}
aadClientSecret: {{ .AzureSPAADClientSecret }}
resourceGroup: {{ .AzureResourceGroup }}
location: {{ .AzureLocation }}
subnetName: {{ .AzureSubnetName }}
securityGroupName: {{ .AzureSecGroupName }}
vnetName: {{ .AzureVnetName }}
routeTableName: {{ .AzureRoutable }}